version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: cvals-cms
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=false
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: cvals-cmd-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
